export interface DbTag {
  label: string;
  cls: string;
}

export interface Platform {
  name: string;
  color: string;
  user: string;
  dbs: DbTag[];
  pages: string[];
}

export const PLATFORMS: Platform[] = [
  {
    name: "AceIQ — marketing performance suite",
    color: "#378ADD",
    user: "Paid media, organic social, lifecycle, SEO teams",
    dbs: [
      { label: "DataMart / Power BI", cls: "datamart" },
      { label: "Marketing intel", cls: "marketing" },
    ],
    pages: [
      "Paid search budget pacing",
      "SQR & bid optimization",
      "Search ad copy testing",
      "Campaign management console",
      "Meta performance",
      "Organic social performance",
      "Influencer campaign reporting",
      "Lifecycle campaign performance",
      "Lifecycle audience & segmentation",
      "Email campaign QA pre-launch",
      "Email brand linting",
      "Promo calendar",
      "Unified launch & campaign calendar",
      "Weekly executive readout",
      "CRO reporting upload",
    ],
  },
  {
    name: "Competitor & market intelligence hub",
    color: "#7F77DD",
    user: "Marketing, PMM, affiliate, SEO teams",
    dbs: [
      { label: "Marketing intel", cls: "marketing" },
      { label: "Market share intel", cls: "marketshare" },
    ],
    pages: [
      "Competitor mention tracker",
      "Competitor press monitor",
      "Competitor price change alerting",
      "SERP rank tracker",
      "Review & sentiment dashboard",
      "State market launch report",
      "Affiliate SERP rank tracker",
      "Content gap finder",
      "Topic & trend monitoring",
      "Market share dashboard",
      "GSC alert view",
      "Ahrefs SEO alerting",
      "Content duplication monitor",
      "SOP & training hub",
      "QA log",
    ],
  },
  {
    name: "Jarvis — course & product ops platform",
    color: "#639922",
    user: "LX, content, product ops, regulatory teams",
    dbs: [
      { label: "Mongo", cls: "mongo" },
      { label: "Regulatory requirements", cls: "regulatory" },
    ],
    pages: [
      "Course creation workflow",
      "Product creation & configuration",
      "Course launch automation",
      "Course versioning",
      "Subtopic assignment (AI)",
      "Question tagging & generation (AI)",
      "Course metadata viewer",
      "Word count analytics",
      "Voiceover & dynamic content pipeline",
      "Accessible audio (image descriptions)",
      "Voiceover pickup queue",
      "Promotions management",
      "Mortgage question review & export",
      "Mortgage course QA checklist",
      "Course topic readouts",
      "DEC content automation",
      "Vertical cheat sheet generator",
      "FRIDAY AI tools (tone, style, content)",
      "Course launch status dashboard",
      "Craft Feedme content ingestion",
      "Craft Feedme content update",
      "Regulatory scraper & monitoring",
      "Regulatory inbox triage",
      "Quarterly state compliance report",
      "Jarvis API key management",
      "Jarvis → Google Calendar sync",
      "Webinar & live CE enrollment",
      "Course re-launch student migration",
    ],
  },
  {
    name: "Affiliate & partner portal",
    color: "#D4537E",
    user: "Affiliate managers, account managers, partners",
    dbs: [
      { label: "B2B intel", cls: "b2b" },
      { label: "DataMart / Power BI", cls: "datamart" },
      { label: "Mongo", cls: "mongo" },
    ],
    pages: [
      "Affiliate self-serve onboarding",
      "Activation status & journey tracker",
      "Partner performance dashboard",
      "Lead quality scoring & routing",
      "BAM leads pipeline",
      "Smart Setter leads pipeline",
      "Groupon redemption processing",
      "Groupon data refresh",
      "TX lead geographic segmentation",
      "Partner content audit",
      "Reactivation sequence manager",
      "Pricing & commission calculator",
      "Voucher portal (tiered access)",
      "Lead form Google Drive upload",
      "DMCA takedown automation",
      "BAM export requirements doc",
      "BAM export user documentation",
      "Affiliate leads pipeline QA",
    ],
  },
  {
    name: "Design & creative intelligence platform",
    color: "#D85A30",
    user: "Design, LX vizcomm, paid media, lifecycle teams",
    dbs: [
      { label: "Design intel", cls: "design" },
      { label: "Marketing intel", cls: "marketing" },
    ],
    pages: [
      "Brand-compliant asset generator",
      "Paid social creative generation",
      "Creative performance tracker",
      "Creative winners library & tagging",
      "Design review & Figma diff tool",
      "Design handoff package generator",
      "AI image generation (Jarvis-integrated)",
      "EDU image responsive delivery",
      "Email brand linting & consistency",
      "LX visual asset automation",
    ],
  },
  {
    name: "Data & analytics workspace",
    color: "#185FA5",
    user: "Data engineering, analytics, finance, FP&A",
    dbs: [
      { label: "DataMart / Power BI", cls: "datamart" },
      { label: "Mongo", cls: "mongo" },
    ],
    pages: [
      "Pipeline failure recovery & monitoring",
      "Snowflake query performance agent",
      "Data quality & taxonomy monitor",
      "Snowflake role & permissions audit",
      "GenBI natural language query tool",
      "FP&A Snowflake agent",
      "Revenue accounting automation (Phase 1)",
      "Revenue accounting automation (Phase 2)",
      "GAAP → MGMT revenue accounting",
      "Vendor contract & forecast reconciliation",
      "Monthly merchant fee analysis",
      "Ecomm change log & anomaly explainer",
      "Matillion AI pipeline agent",
      "Snowflake marketing signal alerting",
      "Engineering analytics (Jellyfish replacement)",
      "Power BI license request automation",
      "BI onboarding reminder",
      "TDLR monthly data request",
    ],
  },
  {
    name: "B2B sales intelligence platform",
    color: "#993556",
    user: "SDRs, AEs, sales ops",
    dbs: [
      { label: "B2B intel", cls: "b2b" },
      { label: "Marketing intel", cls: "marketing" },
      { label: "DataMart / Power BI", cls: "datamart" },
    ],
    pages: [
      "Lead sourcing & enrichment pipeline",
      "Lead scoring & routing engine",
      "HubSpot integration layer",
      "LinkedIn outreach sequence tool",
      "Inbound lead gen & SDR routing",
      "AI voice contact handling",
      "B2B collateral fulfillment portal",
      "Competitive battlecards & sales intel",
      "CRO testing & experimentation",
      "Landing page generator",
    ],
  },
  {
    name: "Student & CX intelligence platform",
    color: "#0F6E56",
    user: "CX, product, student success teams",
    dbs: [
      { label: "Mongo", cls: "mongo" },
      { label: "Marketing intel", cls: "marketing" },
    ],
    pages: [
      "Student review & sentiment dashboard",
      "App store review response tool",
      "Student interaction analytics",
      "Product feedback aggregation & AI agent",
      "Document verification automation",
      "Webinar self-service help & Ada",
      "Research insights tagging & search",
      "Self-serve coupon generation",
      "Ecomm sales & coupon creation",
      "Ecomm product & coupon validation",
    ],
  },
  {
    name: "Regulatory intelligence platform",
    color: "#854F0B",
    user: "Regulatory, product, compliance teams",
    dbs: [
      { label: "Regulatory requirements", cls: "regulatory" },
      { label: "Mongo", cls: "mongo" },
      { label: "DataMart / Power BI", cls: "datamart" },
    ],
    pages: [
      "Regulatory inbox triage & alerting",
      "Regulatory scraper & monitoring dashboard",
      "Quarterly state compliance report generator",
      "TDLR monthly data request automation",
      "Mortgage course QA checklist",
      "Mortgage question review & export",
    ],
  },
  {
    name: "Engineering & dev ops tooling",
    color: "#5F5E5A",
    user: "Engineering, QA, product ops",
    dbs: [
      { label: "Internal / no DB", cls: "internal" },
      { label: "Mongo", cls: "mongo" },
    ],
    pages: [
      "Dev workflow automation (Claude Code)",
      "Feature flag automation tool",
      "QA test data & link generator",
      "Prod/staging promotion automation",
      "Craft CMS cache & Redis layer",
      "Per-page cache invalidation",
      "IDS migration",
      "DNG unified monorepo",
      "Flutter mobile app (experimental)",
      "Iterable API Jira alerts",
      "Analytics instrumentation audit",
      "Product documentation bot",
      "n8n platform evaluation report",
      "Meeting-to-ticket automation",
      "CRO-to-Jira ticket generator",
      "Marketing site code automation",
      "Code-level SEO audit tool",
      "Schema markup generator",
      "Internal API endpoint layer",
      "Infra consolidation & decommission",
      "Dev-web codebase modernization",
      "Identity service migration",
    ],
  },
  {
    name: "PMO & planning workspace",
    color: "#888780",
    user: "PMO, leadership, all teams",
    dbs: [
      { label: "Internal / no DB", cls: "internal" },
      { label: "DataMart / Power BI", cls: "datamart" },
      { label: "Marketing intel", cls: "marketing" },
    ],
    pages: [
      "Company planning & OKR platform",
      "Unified launch & campaign calendar",
      "Course launch status dashboard",
      "Quarterly planning doc automation",
      "OKR & weekly update automation",
      "Meeting notes → Slack automation",
      "Weekly executive readout",
      "Promo calendar integration",
      "n8n platform evaluation",
      "Self-serve automation AI agent",
      "AI topic suggester",
      "AI research & content generator",
      "Blog-to-video repurposing tool",
      "YouTube brief & content optimizer",
      "Organic social content generation",
      "TikTok trend research & brief",
    ],
  },
];

export const DB_STYLES: Record<string, { bg: string; color: string; border: string }> = {
  marketing:   { bg: "#F0EFFF", color: "#3C3489", border: "#C8C4F0" },
  marketshare: { bg: "#E4F5EE", color: "#085041", border: "#A0DFC4" },
  datamart:    { bg: "#E8F2FC", color: "#0C447C", border: "#A8CFF0" },
  mongo:       { bg: "#EBF5E0", color: "#27500A", border: "#AADD80" },
  b2b:         { bg: "#FCE8F2", color: "#72243E", border: "#F0B0D0" },
  design:      { bg: "#FCEEE8", color: "#712B13", border: "#F0C0A8" },
  regulatory:  { bg: "#FDF4E0", color: "#633806", border: "#F0D898" },
  internal:    { bg: "#F2F2EE", color: "#444441", border: "#CCCCCC" },
};

export const FILTERS = [
  { label: "All",            value: "all" },
  { label: "AceIQ",         value: "AceIQ" },
  { label: "Jarvis",        value: "Jarvis" },
  { label: "Competitor",    value: "Competitor" },
  { label: "Affiliate",     value: "Affiliate" },
  { label: "B2B sales",     value: "B2B sales" },
  { label: "Design",        value: "Design" },
  { label: "Data &",        value: "Data &" },
  { label: "Student & CX",  value: "Student" },
  { label: "Regulatory",    value: "Regulatory" },
  { label: "Engineering",   value: "Engineering" },
  { label: "PMO",           value: "PMO" },
];
